# Generated by Django 4.1.1 on 2023-04-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundsObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_fund', models.IntegerField(default=0, verbose_name='Инвестиционный фонд')),
                ('prize_fund', models.IntegerField(default=0, verbose_name='Призовой фонд')),
            ],
            options={
                'verbose_name': 'Объект фонда',
                'verbose_name_plural': 'Объекты фонда',
            },
        ),
    ]
